# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: self-hosted-pool

- cron: "*/5 * * * *"
  displayname: "every hour"
  branches:
  include:
  - main
  always: true

steps:
- task: PowerShell@2
  inputs:
    filePath: 'powershell_task1.ps1'